import { PROPERTY_TYPES } from '../utils/constants'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { jsPDF } from 'jspdf'
import { HiArrowLeft, HiTrendingUp, HiLocationMarker, HiHome, HiDocumentReport, HiCheck, HiShieldCheck } from 'react-icons/hi'
import toast from 'react-hot-toast'

export default function PropertyValuation() {
  const [generated, setGenerated] = useState(false)

  const handleDownload = () => {
    const doc = new jsPDF()
    const today = new Date().toLocaleDateString('en-IN')

    doc.setFontSize(20)
    doc.text('PROPERTY VALUATION REPORT', 105, 25, { align: 'center' })
    doc.setFontSize(10)
    doc.text(`Date: ${today}`, 160, 35)
    doc.text('Report No: VAL-' + Date.now().toString().slice(-6), 160, 42)

    doc.setFontSize(11)
    const lines = [
      'VALUATION SUMMARY',
      '',
      'Estimated Value: \u20B91.25 Cr - \u20B91.45 Cr',
      'Price per sq.ft: \u20B98,500 - \u20B99,800',
      'Confidence Score: 94%',
      '',
      'VALUATION METHODOLOGY',
      '',
      'This valuation is based on:',
      '- Recent comparable sales in the area',
      '- Current market trends and demand-supply dynamics',
      '- Property location, size, and condition analysis',
      '- Government registry data for the region',
      '',
      'MARKET INSIGHTS',
      '',
      'The property market in this area has shown:',
      '- 12% Year-on-Year price appreciation',
      '- Strong demand in the mid-range segment',
      '- Upcoming infrastructure developments within 2km',
      '- Expected 8-10% growth in next quarter',
      '',
      'DISCLAIMER',
      '',
      'This valuation report is for informational purposes only',
      'and should not be considered as professional advice.',
      'Actual market prices may vary based on specific property conditions.',
      '',
      'Generated by Rstate AI Valuation Engine',
      '',
      '_________________________',
      'Authorized Signature',
    ]

    lines.forEach((line, i) => {
      doc.text(line, 20, 55 + i * 7)
    })

    doc.save('Property-Valuation-VAL-' + Date.now().toString().slice(-6) + '.pdf')
    toast.success('PDF report downloaded!')
  }

  return (
    <div className="min-h-screen py-8">
      <div className="max-w-4xl mx-auto px-3 sm:px-4 lg:px-8 py-6 sm:py-8">
        <Link to="/" className="inline-flex items-center gap-2 text-dark-500 hover:text-primary-600 mb-6">
          <HiArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
        <div className="card p-8">
          <div className="flex items-center gap-3 mb-6">
            <span className="text-3xl">📊</span>
            <div>
              <h1 className="text-2xl font-bold font-heading">Property Valuation</h1>
              <p className="text-dark-500">Get accurate market value for your property</p>
            </div>
          </div>

          <div className="grid md:grid-cols-3 gap-4 mb-8">
            <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-xl text-center cursor-pointer hover:bg-blue-100 dark:hover:bg-blue-900/30 transition-colors"
                 onClick={() => toast.success('Location analysis: Property values in this area have appreciated 12% YoY')}>
              <HiLocationMarker className="w-6 h-6 text-blue-500 mx-auto mb-2" />
              <h3 className="font-semibold text-sm">Location Analysis</h3>
              <p className="text-xs text-dark-500">Neighborhood trends & infrastructure</p>
            </div>
            <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-xl text-center cursor-pointer hover:bg-green-100 dark:hover:bg-green-900/30 transition-colors"
                 onClick={() => toast.success('Found 23 comparable properties in this area')}>
              <HiHome className="w-6 h-6 text-green-500 mx-auto mb-2" />
              <h3 className="font-semibold text-sm">Property Comparison</h3>
              <p className="text-xs text-dark-500">Similar listings in your area</p>
            </div>
            <div className="p-4 bg-purple-50 dark:bg-purple-900/20 rounded-xl text-center cursor-pointer hover:bg-purple-100 dark:hover:bg-purple-900/30 transition-colors"
                 onClick={() => toast.success('Market trend: Prices expected to rise 8-10% in next quarter')}>
              <HiTrendingUp className="w-6 h-6 text-purple-500 mx-auto mb-2" />
              <h3 className="font-semibold text-sm">Market Trends</h3>
              <p className="text-xs text-dark-500">Price appreciation forecasts</p>
            </div>
          </div>

          {generated ? (
            <div className="bg-green-50 dark:bg-green-900/20 p-6 rounded-xl mb-6 text-center">
              <HiDocumentReport className="w-12 h-12 text-green-500 mx-auto mb-3" />
              <h2 className="text-lg font-semibold mb-2">Valuation Report Ready!</h2>
              <div className="space-y-2 mb-4">
                <div className="flex items-center justify-center gap-2 text-sm"><HiCheck className="w-4 h-4 text-green-500" /> Estimated Value: ₹1.25 Cr - ₹1.45 Cr</div>
                <div className="flex items-center justify-center gap-2 text-sm"><HiCheck className="w-4 h-4 text-green-500" /> Price per sq.ft: ₹8,500 - ₹9,800</div>
                <div className="flex items-center justify-center gap-2 text-sm"><HiCheck className="w-4 h-4 text-green-500" /> Confidence Score: 94%</div>
              </div>
              <div className="flex justify-center gap-3">
                <button className="btn-primary" onClick={handleDownload}>Download PDF</button>
                <button className="btn-secondary" onClick={() => { setGenerated(false); toast('Reset form') }}>New Valuation</button>
              </div>
            </div>
          ) : (
            <div className="bg-dark-50 dark:bg-dark-800 p-6 rounded-xl mb-6">
              <h2 className="font-semibold mb-4">Get Your Free Valuation Report</h2>
              <div className="grid sm:grid-cols-2 gap-4">
                <select className="input-field" onChange={() => {}}>
                  <option>Select City</option>
                  <option>Mumbai</option><option>Delhi</option><option>Bangalore</option>
                  <option>Hyderabad</option><option>Pune</option><option>Chennai</option>
                  <option>Kolkata</option><option>Ahmedabad</option>
                </select>
                <select className="input-field" onChange={() => {}}>
                  <option>Property Type</option>
                  {Object.values(PROPERTY_TYPES).map(t => <option key={t}>{t}</option>)}
                </select>
                <select className="input-field" onChange={() => {}}>
                  <option>BHK</option>
                  <option>1 BHK</option><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option>
                </select>
                <input type="number" placeholder="Area (sq. ft.)" className="input-field" />
              </div>
              <button className="btn-primary w-full mt-4 flex items-center justify-center gap-2" onClick={() => { setGenerated(true); toast.success('Valuation report generated!') }}>
                <HiDocumentReport className="w-4 h-4" /> Get Valuation
              </button>
            </div>
          )}

          <p className="text-xs text-dark-400 text-center">Our AI-powered valuation uses government registry data and latest market trends for 95%+ accuracy.</p>
        </div>
      </div>
    </div>
  )
}
